import "./globals.css";
import { cn } from "@/lib/utils";
import localFont from "next/font/local";

const texta = localFont({
  src: [
    {
      path: "./fonts/TextaLight.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/TextaRegular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/TextaMedium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/TextaBlack.ttf",
      weight: "700",
      style: "normal",
    },
    // {
    //   path: "./fonts/TextaBold.ttf",
    //   weight: "700",
    //   style: "normal",
    // },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen flex flex-col  antialiased",

          texta.className
        )}
      >
        {children}
      </body>
    </html>
  );
}
